%
%  flight_profile_gen_1.m
%
%  September 2009
%  Copyright (c) 2009 by GPSoft LLC
%  All Rights Reserved.
%

clear all
close all

initpos = [100 200 50];   % initial position
initvtm = 0;   % initial airspeed in meters-per-second

% 
% Note that we are not free to specify pitch and roll since
% these will be dictated by the trim flight condition
initpsi=90*pi/180;       % initial yaw angle

% seg number; duration; v_final; climb_ang; turn-rate; heading_final;
% alt_final; Tinc=0.01s
flightsegf16 = [10 20 75 NaN NaN NaN NaN 0.01;  % Level accel up to 75 meters/sec
                5 NaN 200 NaN NaN 90 50 0.01;  % Level accel up to 200 meters/sec
                7 NaN NaN 5 NaN 90 1500 0.01; % 5 deg climb to altitude of 1500 meters
                5 10 200 NaN NaN 90 1500 0.01;  % Straight-and-level for 10 seconds
                9 NaN 200 NaN -3 270 1500 0.01; % -3 deg/s turn to heading of 270 deg
                5 10 200 NaN NaN 270 1500 0.01;  % Straight-and-level for 10 seconds
                7 NaN 200 5 NaN 270 2500 0.01;  % 5 deg climb to 2500 meters
                5 10 200 NaN NaN 270 2500 0.01;  % Straight-and-level for 10 seconds
                9 NaN 200 NaN 3 90 2500 0.01; % 3 deg/s turn to heading of 90 deg
                5 10 200 NaN NaN 90 2500 0.01;  % Straight-and-level for 5 seconds
                7 NaN 200 5 NaN 90 3500 0.01;  % 5 deg climb to 3500 meters
                5 10 200 NaN NaN 90 3500 0.01;  % Straight-and-level for 10 seconds
                9 NaN 200 NaN -3 270 3500 0.01; % -3 deg/s turn to heading of 270 deg
                5 10 200 NaN NaN 270 3500 0.01;  % Straight-and-level for 10 seconds
                7 NaN 200 5 NaN 270 4500 0.01;  % 5 deg climb to 4500 meters
                5 10 200 NaN NaN 270 4500 0.01;  % Straight-and-level for 10 seconds
                10 1400 200 NaN NaN 270 4500 1;  % Straight-and-level for 1400 seconds
                9 NaN 200 NaN -3 180 4500 0.01; % -3 deg/s turn to heading of 180 deg
                5 10 200 NaN NaN 180 4500 0.01;  % Straight-and-level for 10 seconds
                10 600 200 NaN NaN 180 4500 1];  % Straight-and-level for 600 seconds

profile = profilef16(initpos,initvtm,initpsi,flightsegf16);
time = profile(:,19);   % run time in seconds

fprintf(1,' Calculating Euler Angles \n')
ntot = size(profile,1);
roll = zeros(1,ntot); pitch = roll;  yaw = roll;
for k = 1:ntot,
    dcmnb=[profile(k,10:12); profile(k,13:15); profile(k,16:18)];
    dcmbn=dcmnb';
    eulv=dcm2eulr(dcmbn);
    roll(k) = eulv(1)*180/pi;
    pitch(k) = eulv(2)*180/pi;
    yaw(k) = eulv(3)*180/pi; 
    if yaw(k) < 0, yaw(k)=yaw(k)+360; end
end

save flt_prof_1_dat -V6  % saves a file that is compatible with MATLAB
%                        % version 5 and higher

figure
plot(profile(:,1)*0.001,profile(:,2)*0.001)
axis([-300 50 -200 50])
axis equal
title('Flight Path Generated By FLIGHT PROFILE GEN 1')
xlabel('east (km)')
ylabel('north (km)')
grid

figure
subplot(311)
plot(time/60,profile(:,1))
title('FLIGHT PROFILE GEN 1: Position Components')
ylabel('east pos in m')
subplot(312)
plot(time/60,profile(:,2))
ylabel('north pos in m')
subplot(313)
plot(time/60,profile(:,3))
ylabel('vertical pos in m')
xlabel('run time in minutes')

figure
subplot(311)
plot(time/60,profile(:,4))
title('FLIGHT PROFILE GEN 1: Velocity Components')
ylabel('east vel in m/s')
subplot(312)
plot(time/60,profile(:,5))
ylabel('north vel in m/s')
subplot(313)
plot(time/60,profile(:,6))
ylabel('vertical vel in m/s')
xlabel('run time in minutes')

figure
subplot(311)
plot(time/60,roll)
title('FLIGHT PROFILE GEN 1: Euler Angles')
ylabel('roll angle in deg')
subplot(312)
plot(time/60,pitch)
ylabel('pitch angle in deg')
subplot(313)
plot(time/60,yaw)
ylabel('yaw angle in deg')
xlabel('run time in minutes')
