function vel_prof_L = genvelpr(tc_prof,totvel_prof)
%GENVELPR   Function to generate a velocity profile for a path
%           profile generated by GREATCIR.  Note: path is
%           assumed to be constant altitude.
%
%	vel_prof_L = genvelpr(tc_prof,totvel_prof)
%
%   INPUTS
%       tc_prof = profile of true course from each waypoint
%                 on the great circle route (radians relative
%                 to north; east directions are positive)
%       totvel_prof = vector of total vehicle velocity in knots 
%                     (nautical miles per hour) for each path segment
%
%   OUTPUTS
%       vel_prof_L(i,1:3) = for the i-th path segment, the x,y,z velocity
%                        components (in the local-level frame, ENU) of the vehicle
%                        (velocity is in units of m/s)
%

%	M. & S. Braasch 6-98
%	Copyright (c) 1998 by GPSoft LLC
%	All Rights Reserved.
%

if nargin<2,error('insufficient number of input arguments'),end

nmph2mps = 1.6878*0.3048;

for i = 1:max(size(tc_prof)),
   velmps = totvel_prof(i)*nmph2mps;   %Convert from nautical-miles-per-hour to meters-per-second
   vx = velmps*sin(tc_prof(i));
   vy = velmps*cos(tc_prof(i));
   vel_prof_L(i,1:3) = [vx vy 0];
end

