%
%   dyn_flight_2.m
%
%   Dynamic flight path
%
%  September 2005
%  Copyright (c) 2005 by GPSoft LLC
%  All Rights Reserved.
%
clear all
close all

initpos = [0 0 0];   % initial position
initvel = [0 0 0];   % initial velocity

phi=0*pi/180;       % initial roll angle is zero
theta=0*pi/180;     % initial pitch angle is zero
psi=90*pi/180;       % initial yaw angle

initdcm=eulr2dcm([phi theta psi]);   % Compute initial direction cosine matrix
%                                    % for aircraft attitude (nav-to-body frame)

% seg number; duration; v_final; climb_ang; turn-rate; heading_final;
% turn-delta; Tinc=0.01s
segparf16 = [5 600  200 NaN NaN 90 NaN 1;  % Level flight for 600 sec
             8 NaN NaN NaN -3 NaN NaN 0.005;  % Pitch and roll into a turn
             9 NaN NaN NaN -3 45 -1.945 0.005;  % Turn to heading of 45 deg
             8 NaN NaN NaN 0 NaN NaN 0.005;  % Pitch and roll back to level
             5 1  200 NaN NaN 45 NaN 0.005;  % Level flight for 1 sec
             5 1400  200 NaN NaN 45 NaN 1;  % Level flight for 1400 sec
             8 NaN NaN NaN 3 NaN NaN 0.005;  % Pitch and roll into a turn
             9 NaN NaN NaN 3 90 2.01 0.005;  % Turn to heading of 90 deg
             8 NaN NaN NaN 0 NaN NaN 0.005;  % Pitch and roll back to level
             5 1  200 NaN NaN 90 NaN 0.005;  % Level flight for 1 sec
             5 1400  200 NaN NaN 90 NaN 1];  % Level flight for 1400 sec

profile = progenf16(initpos,initvel,initdcm,segparf16);
time = profile(:,19);   % run time in seconds

h = waitbar(0,'Calculating Euler Angles');
ntot = size(profile,1);
for k = 1:ntot,
    dcmnb=[profile(k,10:12); profile(k,13:15); profile(k,16:18)];
    dcmbn=dcmnb';
    eulv=dcm2eulr(dcmbn);
    roll(k) = eulv(1)*180/pi;
    pitch(k) = eulv(2)*180/pi;
    yaw(k) = eulv(3)*180/pi; 
    if yaw(k) < 0, yaw(k)=yaw(k)+360; end
    waitbar(k/ntot,h)
end
close(h)

%%save dyn_flt_2_dat -V6     % use for MATLAB version 7.x
save dyn_flt_2_dat       % use for MATLAB version 6.x

figure
plot(profile(:,1)*0.001,profile(:,2)*0.001)
axis equal
title('DYN FLIGHT 4: Flight Path Generated By PROGENF16')
xlabel('east (km)')
ylabel('north (km)')
grid

figure
subplot(311)
plot(time,profile(:,4))
title('DYN FLIGHT 4: Velocity Components')
ylabel('east vel in m/s')
subplot(312)
plot(time,profile(:,5))
ylabel('north vel in m/s')
subplot(313)
plot(time,profile(:,6))
ylabel('vertical vel in m/s')
xlabel('run time in seconds')

figure
subplot(311)
plot(time,roll)
title('DYN FLIGHT 4: Euler Angles')
ylabel('roll angle in deg')
subplot(312)
plot(time,pitch)
ylabel('pitch angle in deg')
subplot(313)
plot(time,yaw)
ylabel('yaw angle in deg')
xlabel('run time in seconds')

