%
%   insdem29.m
%
%   Automobile trajectory generator
%   Trajectory generated in a local-level
%   coordinate frame
%
%    03/11/05
%
%
clear all
close all

initpos = [0 0 0];   % initial position
initvel = [0 0 0];   % initial velocity  % MUST BE CONSISTENT WITH EULER ANGLES ! ! !
% initial velocity  % MUST BE CONSISTENT WITH EULER ANGLES ! ! !
%%initvel = [50*sin(pi/4) 50*cos(pi/4) 0];

phi=0*pi/180;       % initial roll angle is zero
theta=0*pi/180;     % initial pitch angle is zero
psi=45*pi/180;       % initial yaw angle

initdcm=eulr2dcm([phi theta psi]);   % Compute initial direction cosine matrix
%                                    % for aircraft attitude (nav-to-body frame)

% seg number; duration; v_final; turn-amount; turn-rate; time-step
segpar_car = [11 10  30  NaN NaN 0.01;  % Level acceleration to 30 m/s 
              11 1   30  NaN NaN 0.01;  % straight for 1 sec
              11 60  30  NaN NaN  1;  % straight for 60 sec
              12 NaN NaN 90  10  0.01;  % Turn right 90 degrees
              11 1   30  NaN NaN 0.01;  % straight for 1 sec
              11 60  30  NaN NaN  1;  % straight for 60 sec
              12 NaN NaN 90  10  0.01;  % Turn right 90 degrees
              11 1   30  NaN NaN 0.01;  % straight for 1 sec
              11 60  30  NaN NaN  1;  % straight for 60 sec
              12 NaN NaN -180  10  0.01;  % Turn right 90 degrees
              11 1   30  NaN NaN 0.01;  % straight for 1 sec
              11 60  30  NaN NaN  1];  % straight for 60 sec

profile = progencar(initpos,initvel,initdcm,segpar_car);
time = profile(:,19);   % run time in seconds

h = waitbar(0,'Calculating Euler Angles');
ntot = size(profile,1);
for k = 1:ntot,
    dcmnb=[profile(k,10:12); profile(k,13:15); profile(k,16:18)];
    dcmbn=dcmnb';
    eulv=dcm2eulr(dcmbn);
    roll(k) = eulv(1)*180/pi;
    pitch(k) = eulv(2)*180/pi;
    yaw(k) = eulv(3)*180/pi; 
    if yaw(k) < 0, yaw(k)=yaw(k)+360; end
    waitbar(k/ntot,h)
end
close(h)


figure
plot(profile(:,1),profile(:,2))
axis equal
title('INSDEM29:  Automobile Path Generated By PROGENCAR')
xlabel('east (meters)')
ylabel('north (meters)')
grid

figure
subplot(311)
plot(time,profile(:,4))
title('INSDEM29:  Velocity Components')
ylabel('east vel in m/s')
subplot(312)
plot(time,profile(:,5))
ylabel('north vel in m/s')
subplot(313)
plot(time,profile(:,6))
ylabel('vertical vel in m/s')
xlabel('run time in seconds')

figure
subplot(311)
plot(time,roll)
title('INSDEM29:  Euler Angles')
ylabel('roll angle in deg')
subplot(312)
plot(time,pitch)
ylabel('pitch angle in deg')
subplot(313)
plot(time,yaw)
ylabel('yaw angle in deg')
xlabel('run time in seconds')

